package descriptions

// ToolDescriptions holds the descriptions for each tool, allowing multiline strings.
var GetDescriptions = map[string]string{
	"get_event": `
Get details about the event that the api key associated with this instance of the server is authorized to access.

Those details include only: the event's title, location, and pricing information. Those details are required for every single event.

Other details about the event, details that are not required for every single event are posted by the event's staff in the widget timeline.

This tool returns information specific to the event context for the current API key.
`,
	"get_widgets": `
Get a list of details about all available widgets in the event's timeline.

Widgets are the primary interface for interacting with the event.
They allow the staff members to post new information about the event such as updates, announcements, and other relevant content.
They can also include interactive features like polls.

Widgets have a unique identifier automatically generated by the server, and a data field with a JSON object containing the widget's data.
The widget's data shape depends on the widget's type and purpose. (POLL, INFO, MARKDOWN, etc.)

This tool provides a list and details of widgets accessible to the current event.
`,

	"get_chat": `
Get complete chat message history of the current event.

The Message object includes the sender's user id, message content, and timestamp.

The chat history is generally not relevant for fetching details about the event itself. But rather about the member's live reactions to the event and to what's happening in the event.
In the live chat, every member of the event can participate in real-time discussions.

Use this tool *ONLY IF the query is related to the chat history itself* and not the event.
`,

	"get_single_widget": `
Get details about a single widget.

This tool provides details of a specific widget accessible to the current event.
`,
}
